jobs:

# linux-x64 build
- job: Linux (rustc 1.23.0)
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.23.0
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  - script: rustup default 1.23.0

  - script: cargo test

# osx-x64 build
- job: OSX (rustc 1.23.0)
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.23.0
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  - script: rustup default 1.23.0

  - script: cargo test

# win-x64 build
- job: Windows (rustc 1.23.0)
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    rustflags: '-C target-feature=+crt-static'
  steps:
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain 1.23.0
  - script: rustup default 1.23.0

  - powershell: |
      $env:PATH = "$env:PATH;$env:USERPROFILE\.cargo\bin"
      cargo test
